version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          
      - run: |
          TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t sturyk/itea-nodejs-app:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push sturyk/itea-nodejs-app:$TAG
