apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: apps
  name: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apps
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: apps
    spec:
      containers:
        - image: sturyk/itea-nodejs-app:1.1.3
          name: nodejs-app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
